-- ============================================================================
-- KensaraAI SEO Pipeline - Complete Supabase PostgreSQL Database Schema
-- ============================================================================

-- 1. Jobs Table (Background Task Queue)
CREATE TABLE IF NOT EXISTS public.jobs (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    job_id       TEXT NOT NULL UNIQUE,
    job_name     TEXT NOT NULL,
    status       TEXT NOT NULL DEFAULT 'pending',
    payload      JSONB DEFAULT '{}'::jsonb,
    result       JSONB DEFAULT '{}'::jsonb,
    error        TEXT,
    retry_count  INT DEFAULT 0,
    created_at   TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    started_at   TIMESTAMPTZ,
    completed_at TIMESTAMPTZ
);
CREATE INDEX IF NOT EXISTS idx_jobs_job_id ON public.jobs(job_id);
CREATE INDEX IF NOT EXISTS idx_jobs_status ON public.jobs(status);

-- 2. Token Cost Log (LLM Token Consumption & Billing Track)
CREATE TABLE IF NOT EXISTS public.token_cost_log (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    job_id            TEXT NOT NULL,
    model_name        TEXT NOT NULL,
    provider          TEXT NOT NULL,
    prompt_tokens     INT DEFAULT 0,
    completion_tokens INT DEFAULT 0,
    total_tokens      INT DEFAULT 0,
    estimated_cost_usd NUMERIC(10, 6) DEFAULT 0.0,
    recorded_at       TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
CREATE INDEX IF NOT EXISTS idx_token_cost_job_id ON public.token_cost_log(job_id);

-- 3. Internal Link Map Table
CREATE TABLE IF NOT EXISTS public.internal_link_map (
    post_id             TEXT PRIMARY KEY,
    post_url            TEXT NOT NULL UNIQUE,
    post_title          TEXT NOT NULL,
    primary_keyword     TEXT NOT NULL,
    cluster_id          TEXT NOT NULL DEFAULT 'general',
    intent_type         TEXT NOT NULL DEFAULT 'informational',
    tier                INT NOT NULL DEFAULT 1,
    date_published      TIMESTAMPTZ,
    date_updated        TIMESTAMPTZ,
    is_pillar           INT NOT NULL DEFAULT 0,
    incoming_link_count INT NOT NULL DEFAULT 0,
    outgoing_link_count INT NOT NULL DEFAULT 0
);

-- 4. RSS Feeds Catalog
CREATE TABLE IF NOT EXISTS public.feeds_catalog (
    feed_id          TEXT PRIMARY KEY,
    url              TEXT,
    type             TEXT,
    last_polled      TIMESTAMPTZ,
    error_count      INT DEFAULT 0,
    score_multiplier NUMERIC(5, 2) DEFAULT 1.0
);

-- 5. Stories Processed (Scraped News & Deduplication)
CREATE TABLE IF NOT EXISTS public.stories_processed (
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    story_id           TEXT UNIQUE,
    source             TEXT,
    headline           TEXT,
    url                TEXT,
    score              INT,
    intent_tag         TEXT,
    fingerprint_vector TEXT,
    processed_at       TIMESTAMPTZ DEFAULT NOW(),
    action_taken       TEXT
);
CREATE INDEX IF NOT EXISTS idx_stories_processed_story_id ON public.stories_processed(story_id);
CREATE INDEX IF NOT EXISTS idx_stories_processed_url ON public.stories_processed(url);

-- 6. Keyword Clusters Catalog
CREATE TABLE IF NOT EXISTS public.keyword_clusters (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cluster_id       TEXT NOT NULL,
    cluster_name     TEXT NOT NULL,
    keyword          TEXT NOT NULL UNIQUE,
    intent_type      TEXT,
    coverage_status  TEXT DEFAULT 'uncovered',
    current_rank     INT,
    monthly_volume   INT DEFAULT 0,
    difficulty_score TEXT,
    last_updated     TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
CREATE INDEX IF NOT EXISTS idx_kc_cluster_id ON public.keyword_clusters(cluster_id);
CREATE INDEX IF NOT EXISTS idx_kc_keyword ON public.keyword_clusters(keyword);

-- 7. Content Production Queue
CREATE TABLE IF NOT EXISTS public.content_queue (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    keyword          TEXT NOT NULL UNIQUE,
    intent_type      TEXT,
    cluster_id       TEXT,
    priority_score   NUMERIC(6, 2) DEFAULT 0.0,
    paa_questions    JSONB DEFAULT '[]'::jsonb,
    tier             INT DEFAULT 2,
    content_type     TEXT DEFAULT 'tier2',
    source           TEXT DEFAULT 'cluster_gap',
    scheduled_for    TIMESTAMPTZ,
    rank_position    INT,
    zero_coverage    INT DEFAULT 0,
    reason           TEXT DEFAULT '',
    status           TEXT DEFAULT 'queued',
    queued_at        TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
CREATE INDEX IF NOT EXISTS idx_cq_status ON public.content_queue(status);

-- 8. Content Calendar Alerts
CREATE TABLE IF NOT EXISTS public.content_calendar_alerts (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    alert_type  TEXT NOT NULL,
    message     TEXT NOT NULL,
    payload     JSONB DEFAULT '{}'::jsonb,
    status      TEXT DEFAULT 'open',
    created_at  TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    resolved_at TIMESTAMPTZ
);
CREATE INDEX IF NOT EXISTS idx_cca_status ON public.content_calendar_alerts(status);

-- 9. AI Visibility (GEO Citation Tracking)
CREATE TABLE IF NOT EXISTS public.ai_visibility (
    id                    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    query                 TEXT NOT NULL,
    engine                TEXT NOT NULL,
    kensara_mentioned     BOOLEAN DEFAULT FALSE,
    position_score        INT,
    sentiment             TEXT,
    competitors_mentioned JSONB DEFAULT '[]'::jsonb,
    checked_at            TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- 10. LinkedIn Metrics
CREATE TABLE IF NOT EXISTS public.linkedin_metrics (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    entity      TEXT NOT NULL,
    metrics     JSONB NOT NULL DEFAULT '{}'::jsonb,
    recorded_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- 11. Entity Status Audits
CREATE TABLE IF NOT EXISTS public.entity_status (
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    platform           TEXT NOT NULL,
    listing_status     TEXT NOT NULL,
    profile_url        TEXT,
    last_audited       TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    completeness_score INT DEFAULT 0
);

-- 12. Unlinked Mentions
CREATE TABLE IF NOT EXISTS public.unlinked_mentions (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    domain          TEXT NOT NULL,
    context_url     TEXT NOT NULL,
    brand_term      TEXT NOT NULL,
    discovered_at   TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    outreach_status TEXT DEFAULT 'pending'
);

-- 13. Founder Brand Mentions
CREATE TABLE IF NOT EXISTS public.founder_brand_mentions (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    source_url    TEXT NOT NULL,
    context       TEXT NOT NULL,
    discovered_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- 14. Content Performance Metrics
CREATE TABLE IF NOT EXISTS public.content_performance (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    keyword       TEXT NOT NULL UNIQUE,
    cluster_id    TEXT,
    intent_type   TEXT,
    word_count    INT,
    h2_structure  JSONB DEFAULT '[]'::jsonb,
    recorded_at   TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- 15. Privacy Enforcement Tracker & Court Judgments
CREATE TABLE IF NOT EXISTS public.enforcement_tracker (
    id           TEXT PRIMARY KEY,
    case_title   TEXT NOT NULL,
    authority    TEXT,
    fine_amount  NUMERIC(12, 2) DEFAULT 0,
    penalty_inr  TEXT,
    date         TEXT,
    summary      TEXT,
    legal_basis  TEXT,
    sector       TEXT,
    status       TEXT,
    url          TEXT,
    updated_at   TIMESTAMPTZ DEFAULT NOW()
);

-- 16. Seen Articles Deduplication
CREATE TABLE IF NOT EXISTS public.seen_articles (
    article_hash TEXT PRIMARY KEY,
    url          TEXT,
    seen_at      TIMESTAMPTZ DEFAULT NOW()
);

-- 17. Activity Log (Dashboard Stream)
CREATE TABLE IF NOT EXISTS public.activity_log (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    action      TEXT NOT NULL,
    item        TEXT,
    status      TEXT,
    details     JSONB DEFAULT '{}'::jsonb,
    created_at  TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- 18. Job History Summary
CREATE TABLE IF NOT EXISTS public.job_history (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    job_id      TEXT NOT NULL,
    job_name    TEXT NOT NULL,
    status      TEXT NOT NULL,
    duration_ms INT DEFAULT 0,
    run_at      TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    details     JSONB DEFAULT '{}'::jsonb
);

-- 19. Platform Statistics & Context
CREATE TABLE IF NOT EXISTS public.platform_stats (
    key         TEXT PRIMARY KEY,
    value       JSONB NOT NULL,
    updated_at  TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- 20. RAG Vector Embeddings Store
CREATE TABLE IF NOT EXISTS public.rag_embeddings (
    id             TEXT PRIMARY KEY,
    collection_key TEXT NOT NULL,
    document       TEXT NOT NULL,
    embedding      JSONB, -- Can be cast to vector type if pgvector extension is enabled
    metadata       JSONB DEFAULT '{}'::jsonb,
    created_at     TIMESTAMPTZ DEFAULT NOW()
);
CREATE INDEX IF NOT EXISTS idx_rag_collection ON public.rag_embeddings(collection_key);
