"""India Localization Engine — Module 2.8.A.

Provides structural context injection at 5 levels for every blog post and
pillar page generated by the SEO Agent pipeline.

This is NOT a facts file and NOT a prompt decorator.
It is a deterministic structural engine. Each function injects context
at a specific structural level of the post-generation pipeline.

Level 1  — Monetary Framing       (deterministic regex pass)
Level 2  — Regulatory Specificity (validates and warns on vague references)
Level 3  — Business Scale         (injects Indian MSME/startup context)
Level 4  — Industry Sector Data   (sector-specific Indian statistics)
Level 5  — Compliance Calendar    (DPDPA enforcement calendar with hedging)
"""

import re
import structlog
from typing import Optional

log = structlog.get_logger()

# ---------------------------------------------------------------------------
# Level 1: Monetary Framing
# ---------------------------------------------------------------------------

# Exchange rate constant — update when RBI rate changes significantly
# Deliberately held as a constant (not live-fetched) for determinism in tests.
USD_TO_INR = 84  # approximate 2025 rate

# Common DPDPA penalty figures in crore (for reference)
DPDPA_PENALTY_MAP = {
    "250 crore": (250, round(250 * 1_00_00_000 / (USD_TO_INR * 1_000_000), 1)),
    "200 crore": (200, round(200 * 1_00_00_000 / (USD_TO_INR * 1_000_000), 1)),
    "50 crore": (50, round(50 * 1_00_00_000 / (USD_TO_INR * 1_000_000), 1)),
    "10 crore": (10, round(10 * 1_00_00_000 / (USD_TO_INR * 1_000_000), 1)),
}

def format_monetary_figure(amount_inr_crore: float, include_usd: bool = True) -> str:
    """Format a monetary figure in ₹ first, then USD in parentheses.

    Per spec 2.8.A Level 1:
    - Never express in USD only
    - Never express in lakhs without also expressing in crore for large figures
    - Always use ₹ symbol, never 'INR'
    """
    crore_str = f"₹{amount_inr_crore:.0f} crore"
    if include_usd:
        usd_million = round(amount_inr_crore * 1_00_00_000 / (USD_TO_INR * 1_000_000), 1)
        return f"{crore_str} (approximately ${usd_million} million USD)"
    return crore_str


def enforce_monetary_framing(text: str) -> str:
    """Deterministic post-processing pass.

    Finds all bare USD amounts and adds ₹ conversion. Also finds ₹ amounts
    expressed without USD parenthetical and adds it. Critically, bare 'USD'
    or '$' amounts in legal penalty sentences are flagged/promoted to ₹-first.
    """
    # Pattern: bare USD amount like "$30 million" or "$30M"
    usd_pattern = re.compile(
        r'\$(\d+(?:\.\d+)?)\s*(?:million|M)\s*(?:USD)?', re.IGNORECASE
    )

    def _usd_to_inr_fmt(m: re.Match) -> str:
        usd_millions = float(m.group(1))
        crore = round((usd_millions * 1_000_000 * USD_TO_INR) / 1_00_00_000, 1)
        return f"₹{crore:.0f} crore (approximately ${usd_millions} million USD)"

    text = usd_pattern.sub(_usd_to_inr_fmt, text)

    # Pattern: ₹ amount without USD parenthetical in penalty sentences
    inr_pattern = re.compile(
        r'(₹(\d+(?:\.\d+)?)\s*crore)(?!\s*\(approximately)',
        re.IGNORECASE
    )

    def _add_usd_parenthetical(m: re.Match) -> str:
        crore_val = float(m.group(2))
        usd_m = round(crore_val * 1_00_00_000 / (USD_TO_INR * 1_000_000), 1)
        return f"{m.group(1)} (approximately ${usd_m} million USD)"

    text = inr_pattern.sub(_add_usd_parenthetical, text)
    return text


# ---------------------------------------------------------------------------
# Level 2: Regulatory Body Specificity
# ---------------------------------------------------------------------------

# Mapping of regulatory domain keywords → correct Indian regulatory body
# Sorted by specificity: more specific domain keywords first so fuzzy matching
# returns the most precise body.
REGULATOR_DOMAIN_MAP = {
    # --- DPDPA-specific ---
    "personal data": "Data Protection Board of India (DPBI)",
    "data principal": "Data Protection Board of India (DPBI)",
    "data fiduciary": "Data Protection Board of India (DPBI)",
    "dpdpa": "Data Protection Board of India (DPBI)",
    "data protection complaint": "Data Protection Board of India (DPBI)",
    "consent manager": "Data Protection Board of India (DPBI)",
    "significant data fiduciary": "Data Protection Board of India (DPBI)",

    # --- MeitY ---
    "data protection policy": "Ministry of Electronics and Information Technology (MeitY)",
    "dpdp rules": "Ministry of Electronics and Information Technology (MeitY)",
    "it act": "Ministry of Electronics and Information Technology (MeitY)",
    "information technology act": "Ministry of Electronics and Information Technology (MeitY)",
    "cyber law": "Ministry of Electronics and Information Technology (MeitY)",
    "digital india": "Ministry of Electronics and Information Technology (MeitY)",

    # --- UIDAI (Aadhaar) — critically missing from original ---
    "aadhaar": "Unique Identification Authority of India (UIDAI)",
    "aadhaar data": "Unique Identification Authority of India (UIDAI)",
    "biometric": "Unique Identification Authority of India (UIDAI)",
    "uid": "Unique Identification Authority of India (UIDAI)",
    "aadhaar-linked": "Unique Identification Authority of India (UIDAI)",
    "aadhaar authentication": "Unique Identification Authority of India (UIDAI)",

    # --- RBI (Banking / Payments) ---
    "banking": "Reserve Bank of India (RBI)",
    "payment data": "Reserve Bank of India (RBI)",
    "upi": "Reserve Bank of India (RBI)",
    "fintech": "Reserve Bank of India (RBI)",
    "nbfc": "Reserve Bank of India (RBI)",
    "payment aggregator": "Reserve Bank of India (RBI)",
    "payment gateway": "Reserve Bank of India (RBI)",
    "digital lending": "Reserve Bank of India (RBI)",
    "credit data": "Reserve Bank of India (RBI)",
    "data localisation": "Reserve Bank of India (RBI)",  # RBI's own localisation mandate

    # --- NPCI (Payment Infrastructure) ---
    "npci": "National Payments Corporation of India (NPCI)",
    "imps": "National Payments Corporation of India (NPCI)",
    "neft": "National Payments Corporation of India (NPCI)",
    "rtgs": "National Payments Corporation of India (NPCI)",
    "rupay": "National Payments Corporation of India (NPCI)",

    # --- SEBI (Securities / Capital Markets) ---
    "securities": "Securities and Exchange Board of India (SEBI)",
    "investment": "Securities and Exchange Board of India (SEBI)",
    "mutual fund": "Securities and Exchange Board of India (SEBI)",
    "demat": "Securities and Exchange Board of India (SEBI)",
    "stock broker": "Securities and Exchange Board of India (SEBI)",
    "portfolio manager": "Securities and Exchange Board of India (SEBI)",

    # --- IRDAI (Insurance) ---
    "insurance": "Insurance Regulatory and Development Authority of India (IRDAI)",
    "insurer": "Insurance Regulatory and Development Authority of India (IRDAI)",
    "policyholder": "Insurance Regulatory and Development Authority of India (IRDAI)",

    # --- PFRDA (Pension) — missing from original ---
    "pension": "Pension Fund Regulatory and Development Authority (PFRDA)",
    "nps": "Pension Fund Regulatory and Development Authority (PFRDA)",
    "national pension": "Pension Fund Regulatory and Development Authority (PFRDA)",

    # --- CERT-In (Cybersecurity) ---
    "cybersecurity": "CERT-In (Indian Computer Emergency Response Team)",
    "cyber incident": "CERT-In (Indian Computer Emergency Response Team)",
    "breach notification": "CERT-In (Indian Computer Emergency Response Team)",
    "ransomware": "CERT-In (Indian Computer Emergency Response Team)",
    "data breach": "CERT-In (Indian Computer Emergency Response Team)",
    "vulnerability": "CERT-In (Indian Computer Emergency Response Team)",

    # --- TRAI (Telecom) ---
    "telecom": "Telecom Regulatory Authority of India (TRAI)",
    "subscriber data": "Telecom Regulatory Authority of India (TRAI)",
    "spectrum": "Telecom Regulatory Authority of India (TRAI)",
    "mobile operator": "Telecom Regulatory Authority of India (TRAI)",
    "call data": "Telecom Regulatory Authority of India (TRAI)",

    # --- DoT (Department of Telecommunications) — different from TRAI ---
    "telecom licence": "Department of Telecommunications (DoT)",
    "telecom policy": "Department of Telecommunications (DoT)",
    "isp licence": "Department of Telecommunications (DoT)",
    "internet service provider": "Department of Telecommunications (DoT)",

    # --- NHA / ABDM (Digital Health) — missing from original ---
    "health data": "National Health Authority (NHA) under MeitY oversight",
    "digital health": "National Health Authority (NHA) under MeitY oversight",
    "abdm": "National Health Authority (NHA)",
    "health records": "National Health Authority (NHA)",
    "ayushman bharat": "National Health Authority (NHA)",

    # --- NMC (Clinical / Medical Data) ---
    "clinical data": "National Medical Commission (NMC)",
    "patient data": "National Medical Commission (NMC)",
    "hospital": "National Medical Commission (NMC)",
    "medical records": "National Medical Commission (NMC)",

    # --- CCPA (Consumer Protection) — missing from original ---
    "consumer data": "Central Consumer Protection Authority (CCPA)",
    "consumer rights": "Central Consumer Protection Authority (CCPA)",
    "e-commerce consumer": "Central Consumer Protection Authority (CCPA)",
    "unfair trade practice": "Central Consumer Protection Authority (CCPA)",
    "dark patterns": "Central Consumer Protection Authority (CCPA)",

    # --- CCI (Competition Law / Data Markets) ---
    "competition": "Competition Commission of India (CCI)",
    "market dominance": "Competition Commission of India (CCI)",
    "antitrust": "Competition Commission of India (CCI)",
    "data monopoly": "Competition Commission of India (CCI)",
    "big tech": "Competition Commission of India (CCI)",
    "merger": "Competition Commission of India (CCI)",

    # --- DPIIT (Startup Recognition) ---
    "startup recognition": "Department for Promotion of Industry and Internal Trade (DPIIT)",
    "dpiit": "Department for Promotion of Industry and Internal Trade (DPIIT)",
    "startup india": "Department for Promotion of Industry and Internal Trade (DPIIT)",
    "recognised startup": "Department for Promotion of Industry and Internal Trade (DPIIT)",

    # --- NABARD (Agriculture / Rural Finance) ---
    "agricultural loan": "National Bank for Agriculture and Rural Development (NABARD)",
    "rural finance": "National Bank for Agriculture and Rural Development (NABARD)",
    "microfinance": "National Bank for Agriculture and Rural Development (NABARD)",
    "farmer data": "National Bank for Agriculture and Rural Development (NABARD)",

    # --- GSTN (Tax / GST) ---
    "gst data": "GST Network (GSTN) under Ministry of Finance",
    "taxpayer data": "GST Network (GSTN) under Ministry of Finance",
    "gstin": "GST Network (GSTN) under Ministry of Finance",

    # --- NCPCR (Children's Data) ---
    "children": "Data Protection Board of India (DPBI)",  # DPDPA primary
    "child data": "DPBI and National Commission for Protection of Child Rights (NCPCR)",
    "minor": "Data Protection Board of India (DPBI)",
    "parental consent": "Data Protection Board of India (DPBI)",

    # --- FSSAI (Food Safety / Food Tech) ---
    "food data": "Food Safety and Standards Authority of India (FSSAI)",
    "food delivery": "Food Safety and Standards Authority of India (FSSAI)",
    "restaurant data": "Food Safety and Standards Authority of India (FSSAI)",
}

# Generic vague regulator phrases to detect and flag
VAGUE_REGULATOR_PHRASES = [
    "the regulator",
    "the authority",
    "regulatory body",
    "the government",
    "the board",
    "authorities",
]


def validate_regulatory_specificity(text: str) -> list[str]:
    """Scan text for vague regulator references and return list of issues.

    Returns a list of actionable warnings to be surfaced in QA.
    Does not modify the text — that is the LLM re-generation's job.
    """
    text_lower = text.lower()
    issues = []
    for vague in VAGUE_REGULATOR_PHRASES:
        if vague in text_lower:
            # Find which domain context it appears in
            domain_hint = None
            for domain_kw, correct_body in REGULATOR_DOMAIN_MAP.items():
                if domain_kw in text_lower:
                    domain_hint = correct_body
                    break
            hint_str = f" (likely should be: {domain_hint})" if domain_hint else ""
            issues.append(
                f"[LEVEL 2] Vague regulator reference: '{vague}' found.{hint_str}"
            )
    return issues


def get_correct_regulator(domain: str) -> str:
    """Return the correct regulatory body name for a given domain.

    Used by the LLM prompt builder to inject the correct regulator into the
    system prompt context per spec 2.8.A Level 2.
    """
    domain_lower = domain.lower()
    for keyword, body in REGULATOR_DOMAIN_MAP.items():
        if keyword in domain_lower:
            return body
    return "Data Protection Board of India (DPBI)"  # safe default for DPDPA content


# ---------------------------------------------------------------------------
# Level 3: Indian Business Scale References
# ---------------------------------------------------------------------------

BUSINESS_SCALE_CONTEXT = {
    "sme": (
        "Indian MSMEs",
        "India has over 63 million MSMEs, most of which process personal data of "
        "their customers and employees and are subject to DPDPA."
    ),
    "msme": (
        "Indian MSMEs",
        "India has over 63 million MSMEs, most of which process personal data of "
        "their customers and employees and are subject to DPDPA."
    ),
    "startup": (
        "Indian startups (including DPIIT-recognised startups)",
        "DPIIT recognition affects DPDPA obligations — recognised startups may "
        "benefit from regulatory sandboxes under MeitY's startup framework."
    ),
    "enterprise": (
        "Indian enterprises and Indian MNCs",
        "Indian enterprises operating across multiple jurisdictions face a dual "
        "compliance burden — DPDPA domestically and GDPR for European data flows."
    ),
    "large company": (
        "Indian enterprises",
        "Large Indian corporates classified as 'Significant Data Fiduciaries' face "
        "the strictest obligations under DPDPA, including mandatory DPO appointment."
    ),
}

BUSINESS_SCALE_REPLACEMENTS = {
    r'\bSMEs\b': 'Indian MSMEs',
    r'\bsmall businesses\b': 'Indian small businesses and MSMEs',
    r'\bstartups\b': 'Indian startups',
    r'\blarge enterprises\b': 'Indian enterprises',
    r'\benterprises\b(?!\s+(?:and|or|Indian|in\s+India))': 'Indian enterprises',
}


def inject_business_scale_context(text: str) -> str:
    """Replace generic scale references with India-specific terminology.

    Per spec 2.8.A Level 3. Applied as a deterministic post-processing pass.
    """
    for pattern, replacement in BUSINESS_SCALE_REPLACEMENTS.items():
        text = re.sub(pattern, replacement, text, flags=re.IGNORECASE)
    return text


def get_business_scale_context_snippet(business_type: str) -> Optional[str]:
    """Return a context snippet for a specific business type.

    Consumed by the brief builder to inject into LLM system prompts.
    """
    key = business_type.lower().strip()
    for k, (label, snippet) in BUSINESS_SCALE_CONTEXT.items():
        if k in key:
            return snippet
    return None


# ---------------------------------------------------------------------------
# Level 4: Industry-Specific Indian Sector Data
# ---------------------------------------------------------------------------

SECTOR_CONTEXT_LIBRARY = {
    "fintech": {
        "statistic": (
            "India's UPI ecosystem processes over 14 billion transactions monthly, "
            "each involving personal financial data subject to DPDPA and RBI data "
            "localisation norms."
        ),
        "regulator": "Reserve Bank of India (RBI)",
        "dpdpa_section": "Section 8 (obligations of Data Fiduciaries), Section 16 (Data Localisation)",
        "risk_level": "HIGH",
    },
    "healthtech": {
        "statistic": (
            "India's digital health records initiative (ABDM) has enrolled over 600 "
            "million citizens, creating extensive personal health data obligations under "
            "DPDPA Section 9 (processing of health data)."
        ),
        "regulator": "MeitY and National Health Authority (NHA)",
        "dpdpa_section": "Section 9 (sensitive personal data processing)",
        "risk_level": "HIGH",
    },
    "edtech": {
        "statistic": (
            "Post-COVID India has 100+ million learners on digital platforms, with "
            "children's data subject to the strictest DPDPA parental consent requirements "
            "under Section 9 and the forthcoming DPDP Rules on verifiable parental consent."
        ),
        "regulator": "Data Protection Board of India (DPBI)",
        "dpdpa_section": "Section 9 (children's data, verifiable parental consent)",
        "risk_level": "HIGH",
    },
    "ecommerce": {
        "statistic": (
            "India's e-commerce sector reached $112 billion (₹9,400 crore) in 2025, "
            "generating consent records for over 400 million active online shoppers — "
            "each a 'Data Principal' with enforceable rights under DPDPA."
        ),
        "regulator": "Data Protection Board of India (DPBI)",
        "dpdpa_section": "Section 7 (consent), Section 12 (right to correction and erasure)",
        "risk_level": "MEDIUM",
    },
    "hrtech": {
        "statistic": (
            "Indian enterprises managing employee data — payroll records, biometric "
            "attendance, performance data — are subject to DPDPA as Data Fiduciaries "
            "for all employee 'Data Principals'."
        ),
        "regulator": "Data Protection Board of India (DPBI)",
        "dpdpa_section": "Section 8 (Data Fiduciary obligations), Section 11 (employer data)",
        "risk_level": "MEDIUM",
    },
    "banking": {
        "statistic": (
            "India's 1.5+ billion bank account holders generate transactional data "
            "processed under a dual regulatory framework: DPDPA (for personal data) "
            "and RBI Master Directions (for financial data localisation)."
        ),
        "regulator": "Reserve Bank of India (RBI)",
        "dpdpa_section": "Section 8 (fiduciary obligations), Section 16 (cross-border transfer)",
        "risk_level": "HIGH",
    },
    "saas": {
        "statistic": (
            "Indian SaaS companies processing data of EU or UK citizens must comply "
            "simultaneously with DPDPA (as processors under Indian law) and GDPR "
            "(as processors under EU law) — creating a dual-compliance obligation."
        ),
        "regulator": "Data Protection Board of India (DPBI) and EDPB",
        "dpdpa_section": "Section 17 (Data Processor obligations), Section 16 (cross-border)",
        "risk_level": "HIGH",
    },
}


def get_sector_context(sector: str) -> Optional[dict]:
    """Return the full sector context dict for a given industry.

    Consumed by the brief builder to inject pre-built statistics and the
    correct sector-specific regulator into LLM generation prompts.
    """
    key = sector.lower().strip()
    # Direct match
    if key in SECTOR_CONTEXT_LIBRARY:
        return SECTOR_CONTEXT_LIBRARY[key]
    # Fuzzy keyword match
    for sector_name, data in SECTOR_CONTEXT_LIBRARY.items():
        if sector_name in key or key in sector_name:
            return data
    return None


def get_sector_statistic(sector: str) -> Optional[str]:
    """Return just the statistic string for a sector."""
    ctx = get_sector_context(sector)
    return ctx["statistic"] if ctx else None


# ---------------------------------------------------------------------------
# Level 5: Compliance Calendar Grounding
# ---------------------------------------------------------------------------

# Authoritative DPDPA enforcement calendar with required hedging language.
# Updated as official notifications come from MeitY.
DPDPA_COMPLIANCE_CALENDAR = [
    {
        "milestone": "DPDP Rules Draft Published",
        "projected_date": "January 2025",
        "status": "CONFIRMED",
        "hedge": "confirmed",
        "description": "Draft Digital Personal Data Protection Rules 2025 published for public consultation.",
    },
    {
        "milestone": "Significant Data Fiduciary (SDF) Classification",
        "projected_date": "Q3 2025",
        "status": "PROJECTED",
        "hedge": "expected",
        "description": (
            "MeitY to publish the list of entities classified as Significant Data "
            "Fiduciaries, triggering DPO appointment and data audit obligations."
        ),
    },
    {
        "milestone": "Consent Manager Registration",
        "projected_date": "Q4 2025",
        "status": "PROJECTED",
        "hedge": "expected to come into effect by",
        "description": (
            "The Consent Manager registration requirement, expected to come into "
            "effect by Q4 2025, means Indian businesses must onboard a registered "
            "Consent Manager for managing Data Principal consent records."
        ),
    },
    {
        "milestone": "DPDPA Full Enforcement Commencement",
        "projected_date": "Q2 2026",
        "status": "PROJECTED",
        "hedge": "projected for",
        "description": (
            "Full DPDPA enforcement by the Data Protection Board, projected for "
            "Q2 2026, pending Consent Manager ecosystem readiness."
        ),
    },
    {
        "milestone": "Verifiable Parental Consent Rules",
        "projected_date": "Q1 2027",
        "status": "PROJECTED",
        "hedge": "projected for",
        "description": (
            "The rules governing verifiable parental consent for processing children's "
            "data, projected for Q1 2027, will require EdTech and gaming companies "
            "to implement identity-verified consent mechanisms."
        ),
    },
]


def get_compliance_calendar_context(milestone_keyword: Optional[str] = None) -> list[dict]:
    """Return the full or filtered DPDPA compliance calendar.

    If milestone_keyword is provided, returns only matching milestones.
    Each entry includes authoritative hedging language per spec 2.8.A Level 5.
    """
    if not milestone_keyword:
        return DPDPA_COMPLIANCE_CALENDAR
    keyword = milestone_keyword.lower()
    return [
        m for m in DPDPA_COMPLIANCE_CALENDAR
        if keyword in m["milestone"].lower() or keyword in m["description"].lower()
    ]


def get_hedged_deadline_phrase(milestone_keyword: str) -> Optional[str]:
    """Return the correctly-hedged deadline sentence for a milestone.

    Per spec 2.8.A Level 5 — all deadlines must use approved hedging language
    ('projected', 'expected', 'as per current DPDP Rules') to avoid legal flags
    while still conveying urgency.
    """
    results = get_compliance_calendar_context(milestone_keyword)
    if results:
        m = results[0]
        return (
            f"The {m['milestone']}, {m['hedge']} {m['projected_date']}, "
            f"means Indian businesses must act now to ensure readiness."
        )
    return None


# ---------------------------------------------------------------------------
# Master Injection Function
# ---------------------------------------------------------------------------

def build_india_context_block(
    sector: Optional[str] = None,
    business_type: Optional[str] = None,
    milestone_keyword: Optional[str] = None,
) -> dict:
    """Assemble the full India localization context block for LLM prompt injection.

    This is the primary output consumed by the brief builder (context/builder.py)
    and the blog writer to prepend authoritative India-specific context into
    every generation pass.

    Returns a structured dict with all 5 levels populated.
    """
    context = {
        "level_1_monetary_note": (
            "Express all financial figures as: ₹[X] crore (approximately $[Y] million USD). "
            "Never use 'INR'. Always use ₹ symbol. Never USD-only."
        ),
        "level_2_regulators": REGULATOR_DOMAIN_MAP,
        "level_3_business_scale": None,
        "level_4_sector_data": None,
        "level_5_calendar": DPDPA_COMPLIANCE_CALENDAR,
    }

    if business_type:
        context["level_3_business_scale"] = get_business_scale_context_snippet(business_type)

    if sector:
        sector_data = get_sector_context(sector)
        if sector_data:
            context["level_4_sector_data"] = sector_data
            log.info("india_context_sector_injected", sector=sector)

    if milestone_keyword:
        hedged = get_hedged_deadline_phrase(milestone_keyword)
        if hedged:
            context["level_5_deadline_phrase"] = hedged

    log.info("india_context_block_built", sector=sector, business_type=business_type)
    return context
