#!/usr/bin/env python3
"""Generate the .env file to import into Vercel, straight from Settings.

    python scripts/make_env_template.py              # writes .env.vercel.example
    python scripts/make_env_template.py --out .env   # for local development

Generated rather than hand-written so the list cannot drift from the code.

Two rules make the output safe to bulk-import:

* A field whose default is meaningful (a model name, a URL) is emitted with
  that default. Emitting it blank would override the default with an empty
  string — pydantic treats "set to empty" and "unset" differently, so a blank
  NVIDIA_MODEL_BLOG breaks model routing rather than falling back.
* A field whose default is empty is emitted blank, ready for a value. No
  "replace_me" placeholders: the app treats those as unset, which is exactly
  the confusing half-state this file exists to avoid.
"""
from __future__ import annotations

import argparse
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parents[1]))

from src.config import Settings  # noqa: E402

#: Read straight from the environment rather than through Settings.
EXTRA_VARS = {
    "CRON_SECRET": ("", "Guards /api/cron/*. Generate: python -c \"import secrets; print(secrets.token_urlsafe(32))\""),
    "GSC_SITE_URL": ("", "Search Console property, e.g. sc-domain:kensara.in"),
}

#: Deliberately omitted, with the reason.
OMITTED = {
    "DATA_DIR": "resolves to /tmp on serverless automatically; setting it wrong breaks writes",
    "CONTENT_OUTPUT_DIR": "computed at runtime from DATA_DIR",
    "GSC_SERVICE_ACCOUNT_FILE": "expects a file on disk; the serverless bundle is read-only",
    "DEBUG_STARTUP": "set it temporarily, by hand, only while diagnosing a failed start",
}

SECTIONS = (
    ("LLM providers", ("GROQ_", "NVIDIA_", "ALLTOKEN_")),
    ("Research and search", ("TAVILY_", "SERPER_", "PERPLEXITY_", "GEMINI_")),
    ("Database", ("SUPABASE_",)),
    ("Publishing", ("WORDPRESS_", "LINKEDIN_", "MAILCHIMP_")),
    ("Search Console", ("GSC_",)),
    ("Platform", ("CRON_", "BLOG_", "NEWS_", "INTEGRATION_")),
)


def collect() -> dict[str, str]:
    values: dict[str, str] = {}
    for name, field in Settings.model_fields.items():
        key = name.upper()
        if key in OMITTED:
            continue
        default = field.default
        if isinstance(default, bool):
            values[key] = "true" if default else "false"
        elif default is None:
            values[key] = ""
        else:
            values[key] = str(default)
    for key, (default, _) in EXTRA_VARS.items():
        values.setdefault(key, default)
    return values


def render(values: dict[str, str]) -> str:
    lines = [
        "# KensaraAI — environment variables",
        "# Generated by scripts/make_env_template.py. Import into Vercel via",
        "# Settings -> Environment Variables -> Import .env, then REDEPLOY:",
        "# variables only reach deployments created after they were saved.",
        "#",
        "# Blank means unset. Do not write replace_me — the app reads placeholder",
        "# values as unset, which looks identical to a missing key.",
        "",
    ]
    placed: set[str] = set()
    for title, prefixes in SECTIONS:
        block = {k: v for k, v in values.items() if k.startswith(prefixes) and k not in placed}
        if not block:
            continue
        placed.update(block)
        lines.append(f"# ── {title} " + "─" * max(0, 60 - len(title)))
        for key in sorted(block):
            note = EXTRA_VARS.get(key, ("", ""))[1]
            if note:
                lines.append(f"# {note}")
            lines.append(f"{key}={block[key]}")
        lines.append("")

    leftover = {k: v for k, v in values.items() if k not in placed}
    if leftover:
        lines.append("# ── Other " + "─" * 52)
        lines.extend(f"{key}={leftover[key]}" for key in sorted(leftover))
        lines.append("")

    lines.append("# Not set here on purpose:")
    lines.extend(f"#   {key} — {why}" for key, why in sorted(OMITTED.items()))
    lines.append("")
    return "\n".join(lines)


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--out", default=".env.vercel.example")
    args = parser.parse_args()

    values = collect()
    Path(args.out).write_text(render(values), encoding="utf-8")

    blanks = sorted(k for k, v in values.items() if not v)
    print(f"Wrote {args.out} — {len(values)} variables, {len(blanks)} awaiting a value:")
    for key in blanks:
        print(f"  {key}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
